# Generated by Django 4.2.16 on 2024-10-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='projects',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Estágio', 'Estágio'), ('1', 'Nível 1'), ('2', 'Nível 2'), ('3', 'Nível 3')], default='Estágio', max_length=10),
        ),
    ]
