# Generated by Django 5.1.2 on 2024-10-25 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_calendarnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='break_time',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='project',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='start_time',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='entrada',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='intervalo',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='saida',
            field=models.TimeField(default='00:00'),
        ),
    ]
